centerConfigs:
- activated: true
  digest: ''
  instanceType: Zookeeper
  name: data_security_ns_test
  namespace: data_security_ns_test
  orchestrationName: data_security_ns_test
  orchestrationType: config_center
  props: {}
  serverLists: 192.168.243.34:12181
